# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dev Linter, Build, Unit Test

env:
  FLUTTER_VERSION: "debug"
  
on:
  push:
    branches: [ developer ]
    paths:
      - Flutter_Demo/**/*
  pull_request:
    branches: [ developer ]
    paths:
      - Flutter_Demo/**/*
defaults:
  run:
    shell: bash
    working-directory: ./Flutter_Demo

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Lint flutter code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      # Add formating standards
      - run: flutter pub get

      # Add formating standards
      - name: Run Linting
        run: flutter analyze
      
      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --${{env.FLUTTER_VERSION}}
        
      - name: Build Web
        run: flutter build web
     
      - name: 'Upload APK Artifact'
        uses: 'actions/upload-artifact@v4'
        with:
          name: hello-flutter-apk-${{env.FLUTTER_VERSION}}
          path: ./build/app/outputs/flutter-apk/*.apk
          
      - name: 'Upload Web Artifacts'
        uses: 'actions/upload-artifact@v4'
        with:
          name: hello-flutter-web-${{env.FLUTTER_VERSION}}
          path: ./build/web/**/*
