# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ppe-umgc-cappms

on:
  push:
    branches:
      - developer
    paths:
      - CaPPMS*/**/*
  pull_request:
    branches:
      - developer
    paths:
      - CaPPMS*/**/*
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Test CAPPMS with dotnet
        run: |
          cd CaPPMSTests
          dotnet test --configuration Release
          
  build:
    runs-on: windows-latest
    needs: test
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
        
      - name: Build CAPPMS with dotnet
        run: |
          cd cappms
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd cappms
          dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F6F7C5E097A14F2DAF78C859EF38BF26 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C5A22B7F4FA445A28DD192D01B809E4D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5ED110D5472447309A35500B538D933E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ppe-umgc-cappms'
          slot-name: 'Production'
          package: .
          
