# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy CaPPMS Container

on:
  pull_request:
    branches:
      - website
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://umgcswen670acr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6485ee65858e43beb573f5232eb994b8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d6bc980048234a28b31747bb7878bc77 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: umgcswen670acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6485ee65858e43beb573f5232eb994b8 }}/cappms-image:${{ github.sha }}
        file: ./CaPPMS/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to CaPPMS Container
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'UMGC-Cappms'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1688327947a14ae38f2e6ad1c5deb14e }}
        images: 'umgcswen670acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6485ee65858e43beb573f5232eb994b8 }}/cappms-image:${{ github.sha }}'
