# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy CaPPMS Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://umgcswen670acr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1cd53a13d461444a8c2dbe2dd68fa2c6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b53239a726fa4c119c1d00c79f4030fe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: umgcswen670acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1cd53a13d461444a8c2dbe2dd68fa2c6 }}/umgcswen670acr/cappms-image:${{ github.sha }}
        file: ./CaPPMS/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to CaPPMS Container
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'UMGC-Cappms'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e1fa7273a6924b35ac3b5be23603707a }}
        images: 'umgcswen670acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1cd53a13d461444a8c2dbe2dd68fa2c6 }}/umgcswen670acr/cappms-image:${{ github.sha }}'
